//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQUISICION
    {
        public int ID { get; set; }
        public decimal MONTO { get; set; }
        public int ID_USUARIO_COMPRADOR { get; set; }
        public int ID_USUARIO_APROBADOR { get; set; }
        public Nullable<int> ID_USUARIO_FINANCIERO { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_APROBADOR { get; set; }
        public Nullable<System.DateTime> FECHA_FINANCIERO { get; set; }
        public int ID_ESTADO { get; set; }
    
        public virtual ESTADO ESTADO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual USUARIO USUARIO1 { get; set; }
        public virtual USUARIO USUARIO2 { get; set; }
    }
}
