'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ESTADO
    Public Property ID As Integer
    Public Property NOMBRE As String
    Public Property CODIGO As String

    Public Overridable Property REQUISICIONs As ICollection(Of REQUISICION) = New HashSet(Of REQUISICION)

End Class
