'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class REQUISICION
    Public Property ID As Integer
    Public Property MONTO As Decimal
    Public Property ID_USUARIO_COMPRADOR As Integer
    Public Property ID_USUARIO_APROBADOR As Integer
    Public Property ID_USUARIO_FINANCIERO As Nullable(Of Integer)
    Public Property FECHA_CREACION As Date
    Public Property FECHA_APROBADOR As Nullable(Of Date)
    Public Property FECHA_FINANCIERO As Nullable(Of Date)
    Public Property ID_ESTADO As Integer

    Public Overridable Property ESTADO As ESTADO
    Public Overridable Property USUARIO As USUARIO
    Public Overridable Property USUARIO1 As USUARIO
    Public Overridable Property USUARIO2 As USUARIO

End Class
