'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class USUARIO
    Public Property ID As Integer
    Public Property NOMBRE As String
    Public Property CORREO As String
    Public Property ID_ROL As Integer
    Public Property USUARIO1 As String
    Public Property CONTRASENNA As String
    Public Property ID_JEFE_APROBADOR As Nullable(Of Integer)

    Public Overridable Property REQUISICIONs As ICollection(Of REQUISICION) = New HashSet(Of REQUISICION)
    Public Overridable Property REQUISICIONs1 As ICollection(Of REQUISICION) = New HashSet(Of REQUISICION)
    Public Overridable Property REQUISICIONs2 As ICollection(Of REQUISICION) = New HashSet(Of REQUISICION)
    Public Overridable Property ROL As ROL

End Class
